// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'bb01b61eaa8841a47d78bbb2caacdca3d5c8b01875c37cdb92023231a77b4199'>;
export type ExecutionHash =
  ExecutionHashBase<'368d3ced1000eef17430b420bdb950b1a2270d66cca41f7d4225503684b324d3'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Appointment: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly petId: CodecTypes['pg/uuid@1']['output'];
      readonly date: CodecTypes['pg/date-string@1']['output'];
      readonly startTime: CodecTypes['pg/time-string@1']['output'];
      readonly durationMinutes: CodecTypes['pg/int4@1']['output'];
      readonly serviceType: 'full_groom' | 'quick_service';
      readonly status: 'scheduled' | 'completed' | 'cancelled';
      readonly source: 'manual' | 'auto_scheduled' | 'waiting_list_approval';
      readonly flaggedReason: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly BlackoutPeriod: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly startDate: CodecTypes['pg/date-string@1']['output'];
      readonly endDate: CodecTypes['pg/date-string@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Owner: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly addressLat: CodecTypes['pg/numeric@1']['output'] | null;
      readonly addressLng: CodecTypes['pg/numeric@1']['output'] | null;
      readonly fixedVisitDay:
        'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday' | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Pet: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ownerId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly breed: CodecTypes['pg/text@1']['output'] | null;
      readonly size: 'small' | 'medium' | 'extra_large';
      readonly isAggressive: CodecTypes['pg/bool@1']['output'];
      readonly groomingFrequency: 'twice_a_month' | 'once_a_month' | 'once_every_two_months' | null;
      readonly needsPickup: CodecTypes['pg/bool@1']['output'];
      readonly locationAddress: CodecTypes['pg/text@1']['output'] | null;
      readonly locationLat: CodecTypes['pg/numeric@1']['output'] | null;
      readonly locationLng: CodecTypes['pg/numeric@1']['output'] | null;
      readonly avgServiceDurationMinutes: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ShopConfig: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly maxPetsPerDay: CodecTypes['pg/int4@1']['output'];
      readonly quickServiceDurationMinutes: CodecTypes['pg/int4@1']['output'] | null;
      readonly openTime: CodecTypes['pg/time-string@1']['output'];
      readonly closeTime: CodecTypes['pg/time-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly WaitingListEntry: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly petId: CodecTypes['pg/uuid@1']['output'];
      readonly preferredStartDate: CodecTypes['pg/date-string@1']['output'] | null;
      readonly preferredEndDate: CodecTypes['pg/date-string@1']['output'] | null;
      readonly status: 'active' | 'fulfilled' | 'cancelled';
      readonly fulfilledAppointmentId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Appointment: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly petId: CodecTypes['pg/uuid@1']['input'];
      readonly date: CodecTypes['pg/date-string@1']['input'];
      readonly startTime: CodecTypes['pg/time-string@1']['input'];
      readonly durationMinutes: CodecTypes['pg/int4@1']['input'];
      readonly serviceType: 'full_groom' | 'quick_service';
      readonly status: 'scheduled' | 'completed' | 'cancelled';
      readonly source: 'manual' | 'auto_scheduled' | 'waiting_list_approval';
      readonly flaggedReason: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly BlackoutPeriod: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly startDate: CodecTypes['pg/date-string@1']['input'];
      readonly endDate: CodecTypes['pg/date-string@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Owner: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly addressLat: CodecTypes['pg/numeric@1']['input'] | null;
      readonly addressLng: CodecTypes['pg/numeric@1']['input'] | null;
      readonly fixedVisitDay:
        'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday' | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Pet: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ownerId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly breed: CodecTypes['pg/text@1']['input'] | null;
      readonly size: 'small' | 'medium' | 'extra_large';
      readonly isAggressive: CodecTypes['pg/bool@1']['input'];
      readonly groomingFrequency: 'twice_a_month' | 'once_a_month' | 'once_every_two_months' | null;
      readonly needsPickup: CodecTypes['pg/bool@1']['input'];
      readonly locationAddress: CodecTypes['pg/text@1']['input'] | null;
      readonly locationLat: CodecTypes['pg/numeric@1']['input'] | null;
      readonly locationLng: CodecTypes['pg/numeric@1']['input'] | null;
      readonly avgServiceDurationMinutes: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ShopConfig: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly maxPetsPerDay: CodecTypes['pg/int4@1']['input'];
      readonly quickServiceDurationMinutes: CodecTypes['pg/int4@1']['input'] | null;
      readonly openTime: CodecTypes['pg/time-string@1']['input'];
      readonly closeTime: CodecTypes['pg/time-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly WaitingListEntry: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly petId: CodecTypes['pg/uuid@1']['input'];
      readonly preferredStartDate: CodecTypes['pg/date-string@1']['input'] | null;
      readonly preferredEndDate: CodecTypes['pg/date-string@1']['input'] | null;
      readonly status: 'active' | 'fulfilled' | 'cancelled';
      readonly fulfilledAppointmentId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly appointments: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly date: CodecTypes['pg/date-string@1']['output'];
      readonly duration_minutes: CodecTypes['pg/int4@1']['output'];
      readonly flagged_reason: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly pet_id: CodecTypes['pg/uuid@1']['output'];
      readonly service_type: 'full_groom' | 'quick_service';
      readonly source: 'manual' | 'auto_scheduled' | 'waiting_list_approval';
      readonly start_time: CodecTypes['pg/time-string@1']['output'];
      readonly status: 'scheduled' | 'completed' | 'cancelled';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly blackout_periods: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly end_date: CodecTypes['pg/date-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'] | null;
      readonly start_date: CodecTypes['pg/date-string@1']['output'];
    };
    readonly owners: {
      readonly address: CodecTypes['pg/text@1']['output'] | null;
      readonly address_lat: CodecTypes['pg/numeric@1']['output'] | null;
      readonly address_lng: CodecTypes['pg/numeric@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fixed_visit_day:
        'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday' | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly pets: {
      readonly avg_service_duration_minutes: CodecTypes['pg/int4@1']['output'] | null;
      readonly breed: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly grooming_frequency:
        'twice_a_month' | 'once_a_month' | 'once_every_two_months' | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly is_aggressive: CodecTypes['pg/bool@1']['output'];
      readonly location_address: CodecTypes['pg/text@1']['output'] | null;
      readonly location_lat: CodecTypes['pg/numeric@1']['output'] | null;
      readonly location_lng: CodecTypes['pg/numeric@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly needs_pickup: CodecTypes['pg/bool@1']['output'];
      readonly owner_id: CodecTypes['pg/uuid@1']['output'];
      readonly size: 'small' | 'medium' | 'extra_large';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly shop_config: {
      readonly close_time: CodecTypes['pg/time-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly max_pets_per_day: CodecTypes['pg/int4@1']['output'];
      readonly open_time: CodecTypes['pg/time-string@1']['output'];
      readonly quick_service_duration_minutes: CodecTypes['pg/int4@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly waiting_list_entries: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fulfilled_appointment_id: CodecTypes['pg/uuid@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly pet_id: CodecTypes['pg/uuid@1']['output'];
      readonly preferred_end_date: CodecTypes['pg/date-string@1']['output'] | null;
      readonly preferred_start_date: CodecTypes['pg/date-string@1']['output'] | null;
      readonly status: 'active' | 'fulfilled' | 'cancelled';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly appointments: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly date: CodecTypes['pg/date-string@1']['input'];
      readonly duration_minutes: CodecTypes['pg/int4@1']['input'];
      readonly flagged_reason: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly pet_id: CodecTypes['pg/uuid@1']['input'];
      readonly service_type: 'full_groom' | 'quick_service';
      readonly source: 'manual' | 'auto_scheduled' | 'waiting_list_approval';
      readonly start_time: CodecTypes['pg/time-string@1']['input'];
      readonly status: 'scheduled' | 'completed' | 'cancelled';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly blackout_periods: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly end_date: CodecTypes['pg/date-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'] | null;
      readonly start_date: CodecTypes['pg/date-string@1']['input'];
    };
    readonly owners: {
      readonly address: CodecTypes['pg/text@1']['input'] | null;
      readonly address_lat: CodecTypes['pg/numeric@1']['input'] | null;
      readonly address_lng: CodecTypes['pg/numeric@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fixed_visit_day:
        'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday' | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly pets: {
      readonly avg_service_duration_minutes: CodecTypes['pg/int4@1']['input'] | null;
      readonly breed: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly grooming_frequency:
        'twice_a_month' | 'once_a_month' | 'once_every_two_months' | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly is_aggressive: CodecTypes['pg/bool@1']['input'];
      readonly location_address: CodecTypes['pg/text@1']['input'] | null;
      readonly location_lat: CodecTypes['pg/numeric@1']['input'] | null;
      readonly location_lng: CodecTypes['pg/numeric@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly needs_pickup: CodecTypes['pg/bool@1']['input'];
      readonly owner_id: CodecTypes['pg/uuid@1']['input'];
      readonly size: 'small' | 'medium' | 'extra_large';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly shop_config: {
      readonly close_time: CodecTypes['pg/time-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly max_pets_per_day: CodecTypes['pg/int4@1']['input'];
      readonly open_time: CodecTypes['pg/time-string@1']['input'];
      readonly quick_service_duration_minutes: CodecTypes['pg/int4@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly waiting_list_entries: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fulfilled_appointment_id: CodecTypes['pg/uuid@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly pet_id: CodecTypes['pg/uuid@1']['input'];
      readonly preferred_end_date: CodecTypes['pg/date-string@1']['input'] | null;
      readonly preferred_start_date: CodecTypes['pg/date-string@1']['input'] | null;
      readonly status: 'active' | 'fulfilled' | 'cancelled';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly appointments: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly pet_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly start_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: false;
                };
                readonly duration_minutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly service_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'scheduled'>;
                  };
                };
                readonly source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flagged_reason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'appointments_pet_id_idx_c47af682';
                  readonly prefix: 'appointments_pet_id_idx';
                  readonly columns: readonly ['pet_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'appointments_date_idx_b4ca319c';
                  readonly prefix: 'appointments_date_idx';
                  readonly columns: readonly ['date'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'appointments';
                    readonly columns: readonly ['pet_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pets';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly blackout_periods: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly start_date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly end_date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly label: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'blackout_periods_start_date_end_date_idx_7bb2ae1b';
                  readonly prefix: 'blackout_periods_start_date_end_date_idx';
                  readonly columns: readonly ['start_date', 'end_date'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly owners: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly address: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly address_lat: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly address_lng: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly fixed_visit_day: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly pets: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly owner_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly breed: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly size: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly is_aggressive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly grooming_frequency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly needs_pickup: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly location_address: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly location_lat: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly location_lng: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly avg_service_duration_minutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'pets_owner_id_idx_ade9f347';
                  readonly prefix: 'pets_owner_id_idx';
                  readonly columns: readonly ['owner_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pets';
                    readonly columns: readonly ['owner_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'owners';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly shop_config: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly max_pets_per_day: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quick_service_duration_minutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly open_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: false;
                };
                readonly close_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly waiting_list_entries: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly pet_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly preferred_start_date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: true;
                };
                readonly preferred_end_date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'active'>;
                  };
                };
                readonly fulfilled_appointment_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['fulfilled_appointment_id'] }];
              indexes: readonly [
                {
                  readonly name: 'waiting_list_entries_pet_id_idx_c47af682';
                  readonly prefix: 'waiting_list_entries_pet_id_idx';
                  readonly columns: readonly ['pet_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'waiting_list_entries_status_idx_e98638ab';
                  readonly prefix: 'waiting_list_entries_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'waiting_list_entries';
                    readonly columns: readonly ['pet_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pets';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'waiting_list_entries';
                    readonly columns: readonly ['fulfilled_appointment_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'appointments';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly AppointmentSource: {
              readonly kind: 'valueSet';
              readonly values: readonly ['manual', 'auto_scheduled', 'waiting_list_approval'];
            };
            readonly AppointmentStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['scheduled', 'completed', 'cancelled'];
            };
            readonly GroomingFrequency: {
              readonly kind: 'valueSet';
              readonly values: readonly ['twice_a_month', 'once_a_month', 'once_every_two_months'];
            };
            readonly PetSize: {
              readonly kind: 'valueSet';
              readonly values: readonly ['small', 'medium', 'extra_large'];
            };
            readonly ServiceType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['full_groom', 'quick_service'];
            };
            readonly WaitingListStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['active', 'fulfilled', 'cancelled'];
            };
            readonly Weekday: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'monday',
                'tuesday',
                'wednesday',
                'thursday',
                'friday',
                'saturday',
                'sunday',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly owners: { readonly namespace: 'public' & NamespaceId; readonly model: 'Owner' };
    readonly pets: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pet' };
    readonly appointments: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Appointment';
    };
    readonly waiting_list_entries: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'WaitingListEntry';
    };
    readonly shop_config: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ShopConfig';
    };
    readonly blackout_periods: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'BlackoutPeriod';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Appointment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly petId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly date: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly startTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly durationMinutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly serviceType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly flaggedReason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly pet: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pet' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['petId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'appointments';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly petId: { readonly column: 'pet_id' };
                readonly date: { readonly column: 'date' };
                readonly startTime: { readonly column: 'start_time' };
                readonly durationMinutes: { readonly column: 'duration_minutes' };
                readonly serviceType: { readonly column: 'service_type' };
                readonly status: { readonly column: 'status' };
                readonly source: { readonly column: 'source' };
                readonly flaggedReason: { readonly column: 'flagged_reason' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly BlackoutPeriod: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly startDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly endDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly label: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'blackout_periods';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly startDate: { readonly column: 'start_date' };
                readonly endDate: { readonly column: 'end_date' };
                readonly label: { readonly column: 'label' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly Owner: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly address: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly addressLat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly addressLng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly fixedVisitDay: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly pets: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pet' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['ownerId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'owners';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly phone: { readonly column: 'phone' };
                readonly address: { readonly column: 'address' };
                readonly addressLat: { readonly column: 'address_lat' };
                readonly addressLng: { readonly column: 'address_lng' };
                readonly fixedVisitDay: { readonly column: 'fixed_visit_day' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Pet: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly ownerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly breed: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly size: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isAggressive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly groomingFrequency: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly needsPickup: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly locationAddress: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly locationLat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly locationLng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly avgServiceDurationMinutes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly appointments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Appointment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['petId'];
                };
              };
              readonly owner: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Owner';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['ownerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly waitingListEntries: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WaitingListEntry';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['petId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pets';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly ownerId: { readonly column: 'owner_id' };
                readonly name: { readonly column: 'name' };
                readonly breed: { readonly column: 'breed' };
                readonly size: { readonly column: 'size' };
                readonly isAggressive: { readonly column: 'is_aggressive' };
                readonly groomingFrequency: { readonly column: 'grooming_frequency' };
                readonly needsPickup: { readonly column: 'needs_pickup' };
                readonly locationAddress: { readonly column: 'location_address' };
                readonly locationLat: { readonly column: 'location_lat' };
                readonly locationLng: { readonly column: 'location_lng' };
                readonly avgServiceDurationMinutes: {
                  readonly column: 'avg_service_duration_minutes';
                };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly ShopConfig: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly maxPetsPerDay: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quickServiceDurationMinutes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly openTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly closeTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'shop_config';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly maxPetsPerDay: { readonly column: 'max_pets_per_day' };
                readonly quickServiceDurationMinutes: {
                  readonly column: 'quick_service_duration_minutes';
                };
                readonly openTime: { readonly column: 'open_time' };
                readonly closeTime: { readonly column: 'close_time' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly WaitingListEntry: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly petId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly preferredStartDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly preferredEndDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fulfilledAppointmentId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly fulfilledAppointment: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Appointment';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['fulfilledAppointmentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly pet: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pet' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['petId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'waiting_list_entries';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly petId: { readonly column: 'pet_id' };
                readonly preferredStartDate: { readonly column: 'preferred_start_date' };
                readonly preferredEndDate: { readonly column: 'preferred_end_date' };
                readonly status: { readonly column: 'status' };
                readonly fulfilledAppointmentId: { readonly column: 'fulfilled_appointment_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
        };
        readonly enum: {
          readonly PetSize: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'small'; readonly value: 'small' },
              { readonly name: 'medium'; readonly value: 'medium' },
              { readonly name: 'extra_large'; readonly value: 'extra_large' },
            ];
          };
          readonly GroomingFrequency: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'twice_a_month'; readonly value: 'twice_a_month' },
              { readonly name: 'once_a_month'; readonly value: 'once_a_month' },
              { readonly name: 'once_every_two_months'; readonly value: 'once_every_two_months' },
            ];
          };
          readonly ServiceType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'full_groom'; readonly value: 'full_groom' },
              { readonly name: 'quick_service'; readonly value: 'quick_service' },
            ];
          };
          readonly AppointmentStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'scheduled'; readonly value: 'scheduled' },
              { readonly name: 'completed'; readonly value: 'completed' },
              { readonly name: 'cancelled'; readonly value: 'cancelled' },
            ];
          };
          readonly AppointmentSource: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'manual'; readonly value: 'manual' },
              { readonly name: 'auto_scheduled'; readonly value: 'auto_scheduled' },
              { readonly name: 'waiting_list_approval'; readonly value: 'waiting_list_approval' },
            ];
          };
          readonly WaitingListStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'active'; readonly value: 'active' },
              { readonly name: 'fulfilled'; readonly value: 'fulfilled' },
              { readonly name: 'cancelled'; readonly value: 'cancelled' },
            ];
          };
          readonly Weekday: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'monday'; readonly value: 'monday' },
              { readonly name: 'tuesday'; readonly value: 'tuesday' },
              { readonly name: 'wednesday'; readonly value: 'wednesday' },
              { readonly name: 'thursday'; readonly value: 'thursday' },
              { readonly name: 'friday'; readonly value: 'friday' },
              { readonly name: 'saturday'; readonly value: 'saturday' },
              { readonly name: 'sunday'; readonly value: 'sunday' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {
    readonly supabase: {
      readonly familyId: 'sql';
      readonly id: 'supabase';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly version: '8.0.0-rc.7';
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'appointments';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'appointments';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'blackout_periods';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'owners';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'owners';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pets';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pets';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'shop_config';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'shop_config';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'waiting_list_entries';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'waiting_list_entries';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
