// Datos mock — puerto directo de docs/prototype/app.js `buildInitialState()`.
// Reemplazar por llamadas a la API real cuando exista el backend NestJS.

import { addDays, toISODate } from "./date-utils";
import type { MockData } from "./types";

export const TODAY_ISO = toISODate(new Date());

export function buildInitialData(): MockData {
  const owners: MockData["owners"] = [
    {
      id: "o1",
      name: "María Fernández",
      phone: "+54 9 11 5555-0101",
      address: "Av. Corrientes 1234, CABA",
      lat: -34.6037,
      lng: -58.3816,
      fixedVisitDay: "saturday",
    },
    {
      id: "o2",
      name: "Diego Torres",
      phone: "+54 9 11 5555-0202",
      address: "Av. Santa Fe 2500, CABA",
      lat: -34.5952,
      lng: -58.4055,
      fixedVisitDay: null,
    },
    {
      id: "o3",
      name: "Lucía Gómez",
      phone: "+54 9 11 5555-0303",
      address: "Av. Rivadavia 4800, CABA",
      lat: -34.6157,
      lng: -58.4333,
      fixedVisitDay: "wednesday",
    },
    {
      id: "o4",
      name: "Pablo Ibarra",
      phone: "+54 9 11 5555-0404",
      address: "Av. Cabildo 2100, CABA",
      lat: -34.5623,
      lng: -58.4562,
      fixedVisitDay: null,
    },
  ];

  const pets: MockData["pets"] = [
    {
      id: "p1",
      ownerId: "o1",
      name: "Rex",
      breed: "Labrador",
      size: "extra_large",
      isAggressive: false,
      groomingFrequency: "once_a_month",
      needsPickup: true,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: 60,
    },
    {
      id: "p2",
      ownerId: "o1",
      name: "Nina",
      breed: "Caniche",
      size: "small",
      isAggressive: false,
      groomingFrequency: "twice_a_month",
      needsPickup: false,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: 30,
    },
    {
      id: "p3",
      ownerId: "o2",
      name: "Toby",
      breed: "Bulldog",
      size: "medium",
      isAggressive: true,
      groomingFrequency: "once_every_two_months",
      needsPickup: true,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: 45,
    },
    {
      id: "p4",
      ownerId: "o3",
      name: "Luna",
      breed: "Border Collie",
      size: "medium",
      isAggressive: false,
      groomingFrequency: null,
      needsPickup: false,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: null,
    },
    {
      id: "p5",
      ownerId: "o4",
      name: "Simón",
      breed: "Schnauzer",
      size: "small",
      isAggressive: false,
      groomingFrequency: "once_a_month",
      needsPickup: true,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: 30,
    },
    {
      id: "p6",
      ownerId: "o2",
      name: "Coco",
      breed: "Shih Tzu",
      size: "small",
      isAggressive: false,
      groomingFrequency: "twice_a_month",
      needsPickup: false,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: 25,
    },
    {
      id: "p7",
      ownerId: "o4",
      name: "Duque",
      breed: "Gran Danés",
      size: "extra_large",
      isAggressive: false,
      groomingFrequency: "once_a_month",
      needsPickup: true,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: 70,
    },
    {
      id: "p8",
      ownerId: "o3",
      name: "Mora",
      breed: "Cocker",
      size: "medium",
      isAggressive: false,
      groomingFrequency: "once_a_month",
      needsPickup: false,
      locationAddress: null,
      lat: null,
      lng: null,
      avgServiceDuration: 40,
    },
  ];

  const appointments: MockData["appointments"] = [
    {
      id: "a1",
      petId: "p1",
      date: TODAY_ISO,
      startTime: "09:00",
      durationMinutes: 60,
      serviceType: "full_groom",
      status: "scheduled",
      source: "manual",
      flaggedReason: null,
    },
    {
      id: "a2",
      petId: "p5",
      date: TODAY_ISO,
      startTime: "10:30",
      durationMinutes: 30,
      serviceType: "full_groom",
      status: "scheduled",
      source: "manual",
      flaggedReason: null,
    },
    {
      id: "a3",
      petId: "p3",
      date: addDays(TODAY_ISO, 1),
      startTime: "11:00",
      durationMinutes: 45,
      serviceType: "full_groom",
      status: "scheduled",
      source: "auto_scheduled",
      flaggedReason: null,
    },
    {
      id: "a4",
      petId: "p2",
      date: addDays(TODAY_ISO, 3),
      startTime: "15:00",
      durationMinutes: 30,
      serviceType: "full_groom",
      status: "scheduled",
      source: "manual",
      flaggedReason: null,
    },
    {
      id: "a5",
      petId: "p1",
      date: addDays(TODAY_ISO, 14),
      startTime: "09:00",
      durationMinutes: 60,
      serviceType: "full_groom",
      status: "scheduled",
      source: "manual",
      flaggedReason: "Excepción: cita dejada dentro de un período de bloqueo",
    },
    {
      id: "a6",
      petId: "p2",
      date: addDays(TODAY_ISO, 21),
      startTime: "09:30",
      durationMinutes: 30,
      serviceType: "full_groom",
      status: "scheduled",
      source: "auto_scheduled",
      flaggedReason: null,
    },
    {
      id: "a7",
      petId: "p5",
      date: addDays(TODAY_ISO, 200),
      startTime: "09:00",
      durationMinutes: 30,
      serviceType: "full_groom",
      status: "scheduled",
      source: "auto_scheduled",
      flaggedReason: null,
    },
    {
      id: "a8",
      petId: "p3",
      date: addDays(TODAY_ISO, -5),
      startTime: "10:00",
      durationMinutes: 45,
      serviceType: "full_groom",
      status: "completed",
      source: "manual",
      flaggedReason: null,
    },
    {
      id: "a9",
      petId: "p1",
      date: addDays(TODAY_ISO, -2),
      startTime: "09:00",
      durationMinutes: 60,
      serviceType: "full_groom",
      status: "cancelled",
      source: "manual",
      flaggedReason: null,
    },
  ];

  const waitingList: MockData["waitingList"] = [
    {
      id: "w1",
      petId: "p6",
      preferredStartDate: null,
      preferredEndDate: null,
      status: "active",
      fulfilledAppointmentId: null,
      createdAt: addDays(TODAY_ISO, -10),
    },
    {
      id: "w2",
      petId: "p8",
      preferredStartDate: null,
      preferredEndDate: null,
      status: "active",
      fulfilledAppointmentId: null,
      createdAt: addDays(TODAY_ISO, -5),
    },
    {
      id: "w3",
      petId: "p7",
      preferredStartDate: null,
      preferredEndDate: null,
      status: "active",
      fulfilledAppointmentId: null,
      createdAt: addDays(TODAY_ISO, -2),
    },
  ];

  const blackoutPeriods: MockData["blackoutPeriods"] = [
    {
      id: "b1",
      startDate: addDays(TODAY_ISO, 12),
      endDate: addDays(TODAY_ISO, 16),
      label: "Vacaciones de invierno",
    },
  ];

  const shopConfig: MockData["shopConfig"] = {
    maxPetsPerDay: 6,
    quickServiceDurationMinutes: 20,
    openTime: "09:00",
    closeTime: "18:00",
  };

  return { owners, pets, appointments, waitingList, blackoutPeriods, shopConfig };
}

// Módulo-singleton: misma identidad durante la sesión del browser, se
// reinicia en cada reload. Suficiente para esta etapa (sin backend); las
// mutaciones locales (ver ConfigView/PickupsView) no persisten entre
// pantallas — eso llega con la API real.
export const mockData: MockData = buildInitialData();
